// <auto-generated />
namespace StackOverflow.Migrations.Custom
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Answertablealter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Answertablealter));
        
        string IMigrationMetadata.Id
        {
            get { return "202009272127577_Answer table alter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
